@echo off
echo Initializing Git repository...
git init
echo Adding remote repository...
git remote remove origin
git remote add origin https://github.com/Vicsicard/ahp-mod-2.0-website-2.0.git
echo Creating .gitignore file...
echo node_modules/ > .gitignore
echo package-lock.json >> .gitignore
echo Adding all files to staging area...
git add .
echo Setting Git user configuration...
git config --global user.email "user@example.com"
git config --global user.name "AHP User"
echo Committing changes...
git commit -m "Revert website to professional design: update components and add server.js"
echo Pushing changes to GitHub...
git push -u origin main --force
echo Done!
pause
